const abi = [
    {
        inputs: [
            { internalType: "address", name: "_factory", type: "address" },
            { internalType: "address", name: "_WETH10", type: "address" },
        ],
        stateMutability: "nonpayable",
        type: "constructor",
    },
    {
        inputs: [{ internalType: "address", name: "target", type: "address" }],
        name: "AddressEmptyCode",
        type: "error",
    },
    {
        inputs: [{ internalType: "address", name: "account", type: "address" }],
        name: "AddressInsufficientBalance",
        type: "error",
    },
    { inputs: [], name: "FailedInnerCall", type: "error" },
    {
        inputs: [{ internalType: "int256", name: "value", type: "int256" }],
        name: "SafeCastOverflowedIntToUint",
        type: "error",
    },
    {
        inputs: [{ internalType: "uint256", name: "value", type: "uint256" }],
        name: "SafeCastOverflowedUintToInt",
        type: "error",
    },
    {
        inputs: [{ internalType: "address", name: "token", type: "address" }],
        name: "SafeERC20FailedOperation",
        type: "error",
    },
    {
        inputs: [],
        name: "WETH10",
        outputs: [{ internalType: "address", name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                components: [
                    { internalType: "address", name: "tokenA", type: "address" },
                    { internalType: "address", name: "tokenB", type: "address" },
                    { internalType: "uint32", name: "indexPool", type: "uint32" },
                    { internalType: "uint256", name: "amountA", type: "uint256" },
                    { internalType: "uint256", name: "amountB", type: "uint256" },
                    { internalType: "uint256", name: "amountMin", type: "uint256" },
                    { internalType: "address", name: "recipient", type: "address" },
                    { internalType: "uint32", name: "deadline", type: "uint32" },
                ],
                internalType: "struct IRouter.AddLiquidityParams",
                name: "params",
                type: "tuple",
            },
        ],
        name: "addLiquidity",
        outputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
        stateMutability: "payable",
        type: "function",
    },
    {
        inputs: [
            {
                components: [
                    { internalType: "uint256", name: "amountIn", type: "uint256" },
                    { internalType: "uint256", name: "amountOutMin", type: "uint256" },
                    { internalType: "address", name: "recipient", type: "address" },
                    { internalType: "bytes", name: "path", type: "bytes" },
                    { internalType: "uint32", name: "deadline", type: "uint32" },
                ],
                internalType: "struct IRouter.ExactInputParams",
                name: "params",
                type: "tuple",
            },
        ],
        name: "exactInput",
        outputs: [{ internalType: "uint256", name: "amountOut", type: "uint256" }],
        stateMutability: "payable",
        type: "function",
    },
    {
        inputs: [
            {
                components: [
                    { internalType: "uint256", name: "amountIn", type: "uint256" },
                    { internalType: "uint256", name: "amountOutMin", type: "uint256" },
                    { internalType: "address", name: "recipient", type: "address" },
                    { internalType: "address", name: "tokenIn", type: "address" },
                    { internalType: "address", name: "tokenOut", type: "address" },
                    { internalType: "uint32", name: "indexPool", type: "uint32" },
                    { internalType: "uint32", name: "deadline", type: "uint32" },
                ],
                internalType: "struct IRouter.ExactInputSingleParams",
                name: "params",
                type: "tuple",
            },
        ],
        name: "exactInputSingle",
        outputs: [{ internalType: "uint256", name: "amountOut", type: "uint256" }],
        stateMutability: "payable",
        type: "function",
    },
    {
        inputs: [
            {
                components: [
                    { internalType: "uint256", name: "amountOut", type: "uint256" },
                    { internalType: "uint256", name: "amountInMax", type: "uint256" },
                    { internalType: "address", name: "recipient", type: "address" },
                    { internalType: "bytes", name: "path", type: "bytes" },
                    { internalType: "uint32", name: "deadline", type: "uint32" },
                ],
                internalType: "struct IRouter.ExactOutputParams",
                name: "params",
                type: "tuple",
            },
        ],
        name: "exactOutput",
        outputs: [{ internalType: "uint256", name: "amountIn", type: "uint256" }],
        stateMutability: "payable",
        type: "function",
    },
    {
        inputs: [
            {
                components: [
                    { internalType: "uint256", name: "amountOut", type: "uint256" },
                    { internalType: "uint256", name: "amountInMax", type: "uint256" },
                    { internalType: "address", name: "recipient", type: "address" },
                    { internalType: "address", name: "tokenIn", type: "address" },
                    { internalType: "address", name: "tokenOut", type: "address" },
                    { internalType: "uint32", name: "indexPool", type: "uint32" },
                    { internalType: "uint32", name: "deadline", type: "uint32" },
                ],
                internalType: "struct IRouter.ExactOutputSingleParams",
                name: "params",
                type: "tuple",
            },
        ],
        name: "exactOutputSingle",
        outputs: [{ internalType: "uint256", name: "amountIn", type: "uint256" }],
        stateMutability: "payable",
        type: "function",
    },
    {
        inputs: [],
        name: "factory",
        outputs: [{ internalType: "address", name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ internalType: "bytes[]", name: "data", type: "bytes[]" }],
        name: "multicall",
        outputs: [{ internalType: "bytes[]", name: "results", type: "bytes[]" }],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [{ internalType: "bytes[]", name: "data", type: "bytes[]" }],
        name: "multicall2",
        outputs: [{ internalType: "bytes[]", name: "results", type: "bytes[]" }],
        stateMutability: "payable",
        type: "function",
    },
    {
        inputs: [],
        name: "refundETH",
        outputs: [],
        stateMutability: "payable",
        type: "function",
    },
    {
        inputs: [
            {
                components: [
                    { internalType: "address", name: "tokenA", type: "address" },
                    { internalType: "address", name: "tokenB", type: "address" },
                    { internalType: "uint32", name: "indexPool", type: "uint32" },
                    { internalType: "uint256", name: "amount", type: "uint256" },
                    { internalType: "uint256", name: "amountAMin", type: "uint256" },
                    { internalType: "uint256", name: "amountBMin", type: "uint256" },
                    { internalType: "address", name: "recipient", type: "address" },
                    { internalType: "uint32", name: "deadline", type: "uint32" },
                ],
                internalType: "struct IRouter.RemoveLiquidityParams",
                name: "params",
                type: "tuple",
            },
        ],
        name: "removeLiquidity",
        outputs: [
            { internalType: "uint256", name: "amount0", type: "uint256" },
            { internalType: "uint256", name: "amount1", type: "uint256" },
        ],
        stateMutability: "payable",
        type: "function",
    },
    {
        inputs: [
            { internalType: "int256", name: "amount0Delta", type: "int256" },
            { internalType: "int256", name: "amount1Delta", type: "int256" },
            { internalType: "bytes", name: "callback", type: "bytes" },
        ],
        name: "swapCall",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            { internalType: "uint256", name: "amountMinimum", type: "uint256" },
            { internalType: "address", name: "recipient", type: "address" },
        ],
        name: "unwrapWETH10",
        outputs: [],
        stateMutability: "payable",
        type: "function",
    },
    { stateMutability: "payable", type: "receive" },
] as const
export default abi
