import Web3, { Address } from "web3"
import {
    KLAYTN_MAINNET_HTTP_RPC_URL,
    KLAYTN_MAINNET_WEBSOCKET_RPC_URL,
    KLAYTN_MAINNET_CONTRACT_FACTORY,
    KLAYTN_MAINNET_CONTRACT_NFT,
    KLAYTN_MAINNET_EXCHANGE_TOKEN,
    KLAYTN_MAINNET_USDT,
    KLAYTN_MAINNET_EXPLORER,
    KLAYTN_MAINNET_CHAIN_NAME,
    KLAYTN_TESTNET_HTTP_RPC_URL,
    KLAYTN_TESTNET_WEBSOCKET_RPC_URL,
    KLAYTN_TESTNET_CONTRACT_FACTORY,
    KLAYTN_TESTNET_CONTRACT_NFT,
    KLAYTN_TESTNET_EXCHANGE_TOKEN,
    KLAYTN_TESTNET_USDT,
    KLAYTN_TESTNET_EXPLORER,
    KLAYTN_TESTNET_CHAIN_NAME,
    KLAYTN_MAINNET_NATIVE_CURRENCY,
    BINANCE_SMART_CHAIN_MAINNET_CHAIN_NAME,
    BINANCE_SMART_CHAIN_MAINNET_CONTRACT_FACTORY,
    BINANCE_SMART_CHAIN_MAINNET_CONTRACT_NFT,
    BINANCE_SMART_CHAIN_MAINNET_EXCHANGE_TOKEN,
    BINANCE_SMART_CHAIN_MAINNET_EXPLORER,
    BINANCE_SMART_CHAIN_MAINNET_HTTP_RPC_URL,
    BINANCE_SMART_CHAIN_MAINNET_USDT,
    BINANCE_SMART_CHAIN_MAINNET_WEBSOCKET_RPC_URL,
    BINANCE_SMART_CHAIN_TESTNET_CHAIN_NAME,
    BINANCE_SMART_CHAIN_TESTNET_CONTRACT_FACTORY,
    BINANCE_SMART_CHAIN_TESTNET_CONTRACT_NFT,
    BINANCE_SMART_CHAIN_TESTNET_EXCHANGE_TOKEN,
    BINANCE_SMART_CHAIN_TESTNET_EXPLORER,
    BINANCE_SMART_CHAIN_TESTNET_HTTP_RPC_URL,
    BINANCE_SMART_CHAIN_TESTNET_USDT,
    BINANCE_SMART_CHAIN_TESTNET_WEBSOCKET_RPC_URL,
    POLYGON_MAINNET_CHAIN_NAME,
    POLYGON_MAINNET_CONTRACT_FACTORY,
    POLYGON_MAINNET_CONTRACT_NFT,
    POLYGON_MAINNET_EXCHANGE_TOKEN,
    POLYGON_MAINNET_EXPLORER,
    POLYGON_MAINNET_HTTP_RPC_URL,
    POLYGON_MAINNET_NATIVE_CURRENCY,
    POLYGON_MAINNET_USDT,
    POLYGON_MAINNET_WEBSOCKET_RPC_URL,
    POLYGON_TESTNET_CHAIN_NAME,
    POLYGON_TESTNET_CONTRACT_FACTORY,
    POLYGON_TESTNET_CONTRACT_NFT,
    POLYGON_TESTNET_EXCHANGE_TOKEN,
    POLYGON_TESTNET_EXPLORER,
    POLYGON_TESTNET_HTTP_RPC_URL,
    POLYGON_TESTNET_NATIVE_CURRENCY,
    POLYGON_TESTNET_USDT,
    POLYGON_TESTNET_WEBSOCKET_RPC_URL,
    BINANCE_SMART_CHAIN_MAINNET_NATIVE_CURRENCY,
    BINANCE_SMART_CHAIN_TESTNET_NATIVE_CURRENCY,
    KLAYTN_TESTNET_BUSD,
    KLAYTN_TESTNET_NKAY,
    KLAYTN_TESTNET_CONTRACT_ROUTER,
    KLAYTN_TESTNET_CONTRACT_WETH10,
    KLAYTN_TESTNET_CONTRACT_QUOTER,
    KLAYTN_TESTNET_CONTRACT_AGGREGATOR,
} from "./chains"

export enum ChainId {
  KlaytnMainnet = 8217,
  KalytnTestnet = 1001,
  PolygonMainnet = 1101,
  PolygonTestnet = 1442,
  BinanceSmartChainTestnet = 97,
  BinanceSmartChainMainnet = 56,
}

export type ChainInfo = {
  httpRpcUrl: string;
  websocketRpcUrl: string;
  factory: Address;
  router: Address;
  WETH10: Address;
  quoter: Address;
  aggregator: Address;
  NFTAddress: Address;
  exchangeToken: Address;
  stableTokens: Address[];
  explorerUrl: string;
  chainName: string;
  nativeCurrency: {
    name: string;
    symbol: string;
    decimals: number;
  };
};

export const defaultChainId = ChainId.KalytnTestnet

export const chainInfos: Record<number, ChainInfo> = {
    [ChainId.KlaytnMainnet]: {
        httpRpcUrl: KLAYTN_MAINNET_HTTP_RPC_URL,
        websocketRpcUrl: KLAYTN_MAINNET_WEBSOCKET_RPC_URL,
        factory: KLAYTN_MAINNET_CONTRACT_FACTORY,
        router: KLAYTN_TESTNET_CONTRACT_ROUTER,
        WETH10: KLAYTN_TESTNET_CONTRACT_WETH10,
        quoter: KLAYTN_TESTNET_CONTRACT_QUOTER,
        aggregator: KLAYTN_TESTNET_CONTRACT_AGGREGATOR,
        NFTAddress: KLAYTN_MAINNET_CONTRACT_NFT,
        exchangeToken: KLAYTN_MAINNET_EXCHANGE_TOKEN,
        stableTokens: [KLAYTN_MAINNET_USDT],
        explorerUrl: KLAYTN_MAINNET_EXPLORER,
        chainName: KLAYTN_MAINNET_CHAIN_NAME,
        nativeCurrency: KLAYTN_MAINNET_NATIVE_CURRENCY,
    },
    [ChainId.KalytnTestnet]: {
        httpRpcUrl: KLAYTN_TESTNET_HTTP_RPC_URL,
        websocketRpcUrl: KLAYTN_TESTNET_WEBSOCKET_RPC_URL,
        factory: KLAYTN_TESTNET_CONTRACT_FACTORY,
        router: KLAYTN_TESTNET_CONTRACT_ROUTER,
        WETH10: KLAYTN_TESTNET_CONTRACT_WETH10,
        quoter: KLAYTN_TESTNET_CONTRACT_QUOTER,
        aggregator: KLAYTN_TESTNET_CONTRACT_AGGREGATOR,
        NFTAddress: KLAYTN_TESTNET_CONTRACT_NFT,
        exchangeToken: KLAYTN_TESTNET_EXCHANGE_TOKEN,
        stableTokens: [
            KLAYTN_TESTNET_USDT,
            KLAYTN_TESTNET_BUSD,
            KLAYTN_TESTNET_NKAY,
        ],
        explorerUrl: KLAYTN_TESTNET_EXPLORER,
        chainName: KLAYTN_TESTNET_CHAIN_NAME,
        nativeCurrency: KLAYTN_MAINNET_NATIVE_CURRENCY,
    },
    [ChainId.PolygonMainnet]: {
        httpRpcUrl: POLYGON_MAINNET_HTTP_RPC_URL,
        websocketRpcUrl: POLYGON_MAINNET_WEBSOCKET_RPC_URL,
        factory: POLYGON_MAINNET_CONTRACT_FACTORY,
        router: KLAYTN_TESTNET_CONTRACT_ROUTER,
        WETH10: KLAYTN_TESTNET_CONTRACT_WETH10,
        quoter: KLAYTN_TESTNET_CONTRACT_QUOTER,
        aggregator: KLAYTN_TESTNET_CONTRACT_AGGREGATOR,
        NFTAddress: POLYGON_MAINNET_CONTRACT_NFT,
        exchangeToken: POLYGON_MAINNET_EXCHANGE_TOKEN,
        stableTokens: [POLYGON_MAINNET_USDT],
        explorerUrl: POLYGON_MAINNET_EXPLORER,
        chainName: POLYGON_MAINNET_CHAIN_NAME,
        nativeCurrency: POLYGON_MAINNET_NATIVE_CURRENCY,
    },
    [ChainId.PolygonTestnet]: {
        httpRpcUrl: POLYGON_TESTNET_HTTP_RPC_URL,
        websocketRpcUrl: POLYGON_TESTNET_WEBSOCKET_RPC_URL,
        factory: POLYGON_TESTNET_CONTRACT_FACTORY,
        router: KLAYTN_TESTNET_CONTRACT_ROUTER,
        WETH10: KLAYTN_TESTNET_CONTRACT_WETH10,
        quoter: KLAYTN_TESTNET_CONTRACT_QUOTER,
        aggregator: KLAYTN_TESTNET_CONTRACT_AGGREGATOR,
        NFTAddress: POLYGON_TESTNET_CONTRACT_NFT,
        exchangeToken: POLYGON_TESTNET_EXCHANGE_TOKEN,
        stableTokens: [POLYGON_TESTNET_USDT],
        explorerUrl: POLYGON_TESTNET_EXPLORER,
        chainName: POLYGON_TESTNET_CHAIN_NAME,
        nativeCurrency: POLYGON_TESTNET_NATIVE_CURRENCY,
    },
    [ChainId.BinanceSmartChainMainnet]: {
        httpRpcUrl: BINANCE_SMART_CHAIN_MAINNET_HTTP_RPC_URL,
        websocketRpcUrl: BINANCE_SMART_CHAIN_MAINNET_WEBSOCKET_RPC_URL,
        factory: BINANCE_SMART_CHAIN_MAINNET_CONTRACT_FACTORY,
        router: KLAYTN_TESTNET_CONTRACT_ROUTER,
        WETH10: KLAYTN_TESTNET_CONTRACT_WETH10,
        quoter: KLAYTN_TESTNET_CONTRACT_QUOTER,
        aggregator: KLAYTN_TESTNET_CONTRACT_AGGREGATOR,
        NFTAddress: BINANCE_SMART_CHAIN_MAINNET_CONTRACT_NFT,
        exchangeToken: BINANCE_SMART_CHAIN_MAINNET_EXCHANGE_TOKEN,
        stableTokens: [BINANCE_SMART_CHAIN_MAINNET_USDT],
        explorerUrl: BINANCE_SMART_CHAIN_MAINNET_EXPLORER,
        chainName: BINANCE_SMART_CHAIN_MAINNET_CHAIN_NAME,
        nativeCurrency: BINANCE_SMART_CHAIN_MAINNET_NATIVE_CURRENCY,
    },
    [ChainId.BinanceSmartChainTestnet]: {
        httpRpcUrl: BINANCE_SMART_CHAIN_TESTNET_HTTP_RPC_URL,
        websocketRpcUrl: BINANCE_SMART_CHAIN_TESTNET_WEBSOCKET_RPC_URL,
        factory: BINANCE_SMART_CHAIN_TESTNET_CONTRACT_FACTORY,
        router: KLAYTN_TESTNET_CONTRACT_ROUTER,
        WETH10: KLAYTN_TESTNET_CONTRACT_WETH10,
        quoter: KLAYTN_TESTNET_CONTRACT_QUOTER,
        aggregator: KLAYTN_TESTNET_CONTRACT_AGGREGATOR,
        NFTAddress: BINANCE_SMART_CHAIN_TESTNET_CONTRACT_NFT,
        exchangeToken: BINANCE_SMART_CHAIN_TESTNET_EXCHANGE_TOKEN,
        stableTokens: [BINANCE_SMART_CHAIN_TESTNET_USDT],
        explorerUrl: BINANCE_SMART_CHAIN_TESTNET_EXPLORER,
        chainName: BINANCE_SMART_CHAIN_TESTNET_CHAIN_NAME,
        nativeCurrency: BINANCE_SMART_CHAIN_TESTNET_NATIVE_CURRENCY,
    },
}

export const GAS_PRICE = Web3.utils.toWei(25, "gwei")
export const GAS_LIMIT = "3000000000"
